version: "3.9"
services: 
  web
    build: .
    ports: 
      - "5000:5000"
    volumes: 
      - .:/code
      - namevolume:/var/log
    links: 
      - redis
  redis
    image: redis
volumes: 
  namevolume:
